#version of docker compose
version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    #change anything will be updated here in docker image
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
