# Generated by Django 3.2.12 on 2022-04-09 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('painting_create_date', models.DateField()),
                ('link_to_instragram', models.CharField(blank=True, max_length=255)),
                ('category', models.ManyToManyField(to='core.Category')),
                ('supply', models.ManyToManyField(to='core.Supply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
