# Generated by Django 3.2.13 on 2022-04-12 23:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_painting'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.painting_image_file_path),
        ),
    ]
